name: Publish to NPM

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: node - setup
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      # pnpm stuff
      - name: pnpm - install
        run: npm i pnpm@latest -g
      - name: pnpm - config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: pnpm - install
        run: pnpm install

      # build
      - name: build
        run: pnpm run build

      # publish to npm
      - name: release
        id: changesets
        uses: changesets/action@master
        with:
          publish: pnpm run release
          version: pnpm version-packages
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
