name: CD

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: node - setup
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      # pnpm stuff
      - name: pnpm - install
        run: npm i pnpm@latest -g
      - name: pnpm - config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - name: pnpm - install
        run: pnpm install

      # build
      - name: build
        run: pnpm run build

      # publish to npm
      - name: release
        id: changesets
        uses: changesets/action@master
        with:
          publish: pnpm run release
          version: pnpm version-packages
          commit: 'chore: version packages'
          title: 'chore: version packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

# name: Publish
# on:
#   workflow_run:
#     workflows: [CI]
#     branches: [main]
#     types: [completed]

# concurrency: ${{ github.workflow }}-${{ github.ref }}

# permissions:
#   contents: write
#   pull-requests: write

# jobs:
#   publish:
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: pnpm/action-setup@v2
#         with:
#           version: 8
#       - uses: actions/setup-node@v3
#         with:
#           registry-url: 'https://registry.npmjs.org'


#           node-version: 20.x
#           cache: "pnpm"

#       - run: npm config set registry https://registry.npmjs.org/ 
#       - run: pnpm install --no-frozen-lockfile

#       - name: Creating .npmrc
#         run: |
#           cat << EOF > "$HOME/.npmrc"
#             //registry.npmjs.org/:_authToken=$NPM_TOKEN
#           EOF
#         env:
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
#       - name: Create Release Pull Request or Publish
#         id: changesets
#         uses: changesets/action@v1
#         with:
#           publish: pnpm run release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

