name: Publish to NPM

on:
  push:
    branches:
      - main

env:
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      # env stuff
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

        # setup node
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.2"

      # Pnpm stuff
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.5
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      # build
      - name: build
        run: pnpm run build

      - name: Set Git Credentials
        run: |
          git config user.name "${GITHUB_ACTOR}" 
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Release It 🚀
        run: pnpm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
